project:
  type: website
  output-dir: docs
  render:
    - environmental-data-compilation.qmd
    - 01-data-compilation.qmd
    - 02-overview-seasonality-stats.qmd
    - 03-periodicity-recurrence.qmd
    - 04-trophic-assignment-taxa-profile.qmd


website:
  title: "IFCB analysis | Port Aransas"
  navbar:
    left:
      - href: environmental-data-compilation.qmd
        text: Collect environmental data
      - href: 01-data-compilation.qmd
        text: Import counts & add metadata
      - href: 02-overview-seasonality-stats.qmd
        text: Overview of data
      - href: 03-periodicity-recurrence.qmd
        text: Evaluate periodic signals
      - href: 04-trophic-assignment-taxa-profile.qmd
        text: Trophic assignment & taxa profiles
      

format:
  html:
    theme: minty
    css: styles.css
    code-fold: true
    toc: true
    toc-location: left
    number-sections: true
    number-depth: 2


